### PR TITLE
Allows to specify how many (future) month should be displayed

### PR DESCRIPTION
**Pull request by EbilPanda**
This PR introduce new setting-var: `countNextMonths`as a number equal or greater than 1 (act-month - 'infinite') with the default setting or 3 month as it is now.

PS: I had to remove the .gitignore line for dist to get it to load with ionic -> is the .gitignore 'fix' from last week intended?

### CODE REVIEW

**Comment by EbilPanda** [comment]
sry the PR gets polluted by other commits I'm currently testing...don't know how to disable this

**Comment by HsuanXyz** [comment]
@EbilPanda 
Hi, Thank you for your PR!
But now can not release the new version, please revoke your changes for `README.md`&`package.json`,  then I will merge.

**Comment by bragayann** [comment]
Hey @EbilPanda, really nice contribution!

- Check until which commit you want to have to this PR.
- Get its hash
- Do `git reset --hard yourhash`. example: `git reset --hard b3d637b` for the updated readme... one
- Force push the repo like `git push origin -u yourbranch -f`

I'd recommend you to create a new branch based on your current one(just for backup), though.

**Comment by EbilPanda** [comment]
I have gone back on my baster branch and also made a branch out of it :)
will make the other feature I'm currently on directly as a branch :)

hope everything is okay now -> have removed readme commit and revert the change to package.json

**Pull request merged**
