### PR TITLE
Feature/ionic 4 migration

### PR DESCRIPTION
**Pull request by ulesta**
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Demos changes
[ ] Other... Please describe:
```

## What is the current behavior?
Core lib is not compatible with Ionic v4.

Issue Number: #193 

## What is the new behavior?
Core lib is now compatible with Ionic v4.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

## Other information
Demo: https://www-muyygoxqox.now.sh

### CODE REVIEW

**Comment by ulesta** [comment]
I'll be reopening this, just getting an initial review from my colleagues. Feel free to leave comments now as well.

**Comment by ulesta** [comment]
I'll be working on updating documentation next. After that, I'll update`demo/` and `demo-lazyload/`

**Comment by ulesta** [comment]
Here's a demo: https://www-wfadzalbha.now.sh/home

**Comment by adamduren** [comment]
Is this a backwards compatible or breaking change?

**Comment by ulesta** [comment]
Hey @adamduren ! These are breaking changes, only compatible with Ionic 4.

**Comment by aleksander351** [comment]
how to install the updated package?

**Comment by adamduren** [comment]
@ulesta Is it possible to get a beta build for this?

**Comment by msd117** [comment]
Is there any backup copy for IONIC 3?

**Pull request merged**
