### PR TITLE
Add isToday flag to calendar day object

### PR DESCRIPTION
**Pull request by yannbf**
This PR does the following:
* Fixes a small typo on components folder (from `compopnents` to `components`)
* Adds isToday variable on calendar day
* Highlights today date with a thin border

### CODE REVIEW

**Comment by yannbf** [comment]
By the way, I wanted to ask two things:
- When I run `npm run-script build` it takes like 10 minutes to build. Do you have any idea why?
- Isn't the /dist folder supposed to be on .gitignore?

**Comment by yannbf** [comment]
Sample of the change:

selection_286

**Comment by HsuanXyz** [comment]
> English is not my native language; please excuse typing errors.

Thank you very much for your PR😀

Replace `isToday` with `borderHighlights`, maybe better appropriate.

I run `npm run-script build`, only  few seconds.  I'd love to help you, what do you need me to offer?

**Comment by yannbf** [comment]
English is not mine either, and yours is very good, don't worry.

It actually would be nice to expose that flag to the dev, because there may be a case where the dev has to know if the selected day is today, so she/he wouldn't need to use any logic, as it's already there. What do you think?

I have no idea why my build takes so long. I think I'll update my node (currently 6.9.1) and see if that changes anything.
I really like your project and I'm willing to contribute more, let me know if you have anything down on the road to be done!

**Comment by HsuanXyz** [comment]
First thank you for taking the time to read my code.
I will merge your PR and then refactor the my code.

**Pull request merged**
