### PR TITLE
Ion Icons 5 update

### LINKED ISSUE #312: ion2 calender not showing ios-arrow-forword & ios-arrow-back with latest ionic 5
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ ] **3.x**
[ ] **4.x**

**Ion2-calendar mode:**  (check one with "x")
[ ] components mode
[ ] modal mode

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] help me

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
```

### PR DESCRIPTION
**Pull request by itsLucario**
Fixes:  #312
## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Demos changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #313 

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by Tonio-lavanda** [comment]
Is this PR going to be reviewed and merged ?

**Comment by itsLucario** [comment]
@Tonio-lavanda Not sure, I think repo maintainer is not active. You can use my fork if you need the change.

**Comment by julienkermarec** [comment]
@itsLucario how to use your fork ? i have tried : npm i itsLucario/ion2-calendar  but it doesnt work

**Comment by jeffreyramia** [comment]
+1 merge

**Comment by lukeisontheroad** [comment]
+1 mege

**Comment by itsLucario** [comment]
I have published my fork to @lucario/ion5-calendar

You can use it with `npm i @lucario/ion5-calendar`

**Pull request merged**
